name: fly
mcp:
  - url: https://mcp-notes.jon-winsley.workers.dev/sse
    authorization:
      bearer: ${{ env.MCP_NOTES_KEY }}
    approvedTools:
      - createNote
      - readNote
      - listNotes
      - deleteNote
      - updateNote
