clients:
  github:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - -e
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - ghcr.io/github/github-mcp-server
    agent:
      enabled: false

  memory:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - -e
      - MEMORY_FILE_PATH=/data/memory.json
      - -v
      - ./data/memory:/data
      - mcp/memory
    agent:
      enabled: false

  filesystem:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - --mount
      - type=bind,src=./data/files,dst=/data
      - mcp/filesystem
      - /data
    agent:
      enabled: false

  fetch:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - mcp/fetch
    agent:
      enabled: false

  brave-search:
    type: stdio
    command: docker
    args:
      - run
      - -i
      - --rm
      - -e
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - mcp/brave-search
    agent:
      enabled: false
